language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
#  Looks like travis-ci doesn't support 3.3 yet:
#  https://github.com/pypa/virtualenv/issues/329
  - "3.3"
  - "pypy"
install: "pip install . -r requirements.txt -f 3rdparty/which/index.html --use-mirrors"
script: python setup.py test
